// Package triggers renders the tmux.conf fragment that wires tmux-remux into a
// tmux server. It is the single source of truth for every hook, bind and option
// tmux-remux installs: tmux-remux.tmux pipes Render's output into
// `tmux source-file -`, and examples/tmux.conf is a generated copy of it.
//
// tmux 3.8 replaced notifications with events carrying key/value payloads, so
// a hook sees #{hook_<key>} only for keys its event set. That changes which
// format strings are correct, which is why Render takes a version.
package triggers

import (
	"regexp"
	"strings"

	"github.com/noamsto/tmux-remux/internal/tmux"
)

// Params configures a render.
type Params struct {
	// Bin is the tmux-remux path the hooks invoke.
	Bin string
	// Version is the tmux the fragment targets.
	Version tmux.Version
	// AutoRestore emits the restore --auto line.
	AutoRestore bool
}

const binToken = "@BIN@"

// bareBin matches paths needing no shell quoting inside a hook command.
var bareBin = regexp.MustCompile(`^[A-Za-z0-9._/-]+$`)

// quoteBin makes bin survive as one shell word inside a hook command string.
// tmux config quoting has no backslash escape, so a literal quote is spliced
// with:
//
//	'\''
//
// which closes the hook's own single-quoted argument, emits a quote, and
// reopens it. Paths needing no quoting are left bare so the generated
// examples/tmux.conf stays readable.
func quoteBin(bin string) string {
	if bareBin.MatchString(bin) {
		return bin
	}
	return `'\''` + bin + `'\''`
}

const headerLegacy = `# tmux-remux wiring — generated by ` + "`tmux-remux triggers`" + `; do not edit by hand.
# Targets tmux < 3.8.

`

const saveHooks = `# Save snapshots on structural change
# after-split-window stands in for the pane-created hook tmux doesn't have: without it
# a new pane reaches no snapshot until the next window/session event, and undo can
# only restore what a snapshot recorded.
set-hook -g session-created     'run-shell -b "@BIN@ save --reason=hook:session-created"'
set-hook -g window-linked       'run-shell -b "@BIN@ save --reason=hook:window-linked"'
set-hook -g after-split-window  'run-shell -b "@BIN@ save --reason=hook:after-split-window"'
set-hook -g client-detached     'run-shell -b "@BIN@ save --reason=hook:client-detached"'

`

// killPaneHook is version-independent: no tmux release gives a command hook the
// pane it killed.
const killPaneHook = `# prefix+x kills the pane without its program exiting, so pane-exited never fires.
# after-kill-pane is a command hook with no hook_pane; the id is recovered by diffing
# the survivors against the last snapshot.
set-hook -g after-kill-pane    'run-shell -b "@BIN@ capture-event pane-died"'
`

// windowSessionHooks are version-independent: window-unlinked and
// session-closed carry session and session_name in their 3.8 payloads too.
const windowSessionHooks = `set-hook -g window-unlinked    'run-shell -b "@BIN@ capture-event window-unlinked    --window=#{hook_window} --session='\''#{hook_session}'\'' --session-name='\''#{hook_session_name}'\''"'
set-hook -g session-closed     'run-shell -b "@BIN@ capture-event session-closed     --session='\''#{hook_session}'\'' --session-name='\''#{hook_session_name}'\''"'

`

// closeHooks captures close events on every supported tmux.
//
// pane-exited's payload sets pane, window and exit status but no session, so
// #{hook_session} and #{hook_session_name} expand empty there — measured on
// 3.7b and next-3.8 alike. It reads the event target instead.
//
// window-unlinked and session-closed keep hook_*: their payloads do carry the
// session, and on session-closed the target does not — the session is already
// dead, so the target falls back to an unrelated live one.
const closeHooks = `# Capture close events for undo
# Hook pane-exited (pane-died only fires with remain-on-exit); kind stays "pane-died" for the diff
# pane-exited carries no session in its payload on any tmux tested, so --session
# and --session-name read the event target instead of #{hook_session}.
# Both are quoted so a $-prefixed id or a name with spaces stays one shell word;
# the '\'' splices in a literal quote without ending this line's own
# single-quoted argument (tmux's config quoting has no backslash escape). An
# unquoted $38 would read as positional parameter $3 followed by a literal 8,
# confusing the cascade dedup in closeevent.Capture.
set-hook -g pane-exited        'run-shell -b "@BIN@ capture-event pane-died          --pane=#{hook_pane}    --window=#{hook_window} --session='\''#{session_id}'\'' --session-name='\''#{session_name}'\''"'
` + killPaneHook + windowSessionHooks

const header38 = `# tmux-remux wiring — generated by ` + "`tmux-remux triggers`" + `; do not edit by hand.
# Targets tmux 3.8+.

`

// monitorSave replaces the external 60s save timer with a server-side monitor
// hook. #{t:%M} does NOT work: t: formats a time *variable*, not
// strftime-of-now. T: re-expands a variable's value through strftime, so the
// format string has to live in an option. The monitor evaluates once a second
// and fires when the value changes — once a minute.
//
// The hook is global, which matters: a global monitor is bound to no session,
// so it falls back to the lowest-id live session and keeps firing across
// session churn. It goes quiet only when no session exists, which is exactly
// when a timer save is a no-op.
const monitorSave = `# Periodic snapshot floor (tmux 3.8 monitor hook — replaces an external timer)
set -g @remux_save_tick '%M'
set-hook -g -B '@remux-save:session:#{T:@remux_save_tick}' 'run-shell -b "@BIN@ save --reason=timer"'

`

const autoRestore = `# Auto-restore on tmux start
run-shell -b '@BIN@ restore --auto'

`

const binds = `# Keybindings
bind   u    run-shell "@BIN@ undo --pop --session='#{session_name}'"
bind   U    display-popup -E -w 90% -h 85% '@BIN@ pick --kind=close'
bind   R    display-popup -E -w 90% -h 85% '@BIN@ pick --kind=snapshot'
bind C-s    run-shell '@BIN@ save --reason=keybinding'
`

// Render returns the tmux.conf fragment wiring tmux-remux into a tmux server.
func Render(p Params) string {
	modern := p.Version.AtLeast(3, 8)

	var s strings.Builder
	if modern {
		s.WriteString(header38)
	} else {
		s.WriteString(headerLegacy)
	}
	s.WriteString(saveHooks)
	if modern {
		s.WriteString(monitorSave)
	}
	s.WriteString(closeHooks)
	if p.AutoRestore {
		s.WriteString(autoRestore)
	}
	s.WriteString(binds)
	return strings.ReplaceAll(s.String(), binToken, quoteBin(p.Bin))
}
